language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc

  - os: linux
    compiler: clang

  - os: windows

script:
  - cmake --version
  - mkdir src/build
  - cd src/build
  - cmake ..
  - cmake  --build .

git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

branches:
  only:
  - master

notifications:
  email: false
