language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc

  - os: linux
    compiler: clang

  - os: osx
    compiler: clang

  - os: windows

script:
  - cmake --version
  - mkdir src/build
  - cd src/build
  - cmake ..
  - cmake  --build .

branches:
  only:
  - master

notifications:
  email: false
