language: cpp
compiler:
  - clang
  - gcc

os:
  - windows

script:
  - cmake --version
  - mkdir src/build
  - cd src/build
  - cmake ..
  - cmake  --build .
  - ls Debug

branches:
  only:
  - master

notifications:
  email: false
