language: cpp
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

script:
  - cmake --version
  - mkdir src/build
  - cd src/build
  - cmake ..
  - cmake  --build .

branches:
  only:
  - master

notifications:
  email: false
