language: cpp
dist: bionic
sudo: false

os:
- linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - cd src
  - g++-6 main.cpp -O3

branches:
  only:
  - master

notifications:
  email: false
