language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc

  - os: linux
    compiler: clang

  - os: osx
    osx_image: xcode8
    env:
      - MATRIX_EVAL="brew install gcc && CC=gcc-7 && CXX=g++-7"
    before_install:
      - eval "${MATRIX_EVAL}"

  - os: osx
    compiler: clang

  - os: windows

script:
  - cmake --version
  - mkdir src/build
  - cd src/build
  - cmake ..
  - cmake  --build .

branches:
  only:
  - master

notifications:
  email: false
